### ISSUE TITLE
Update README to include enabling Privileged Gateway Intents

### ISSUE THREAD

**Issue by dreiekk** [Maveo/Spark#53]
### Describe the Bug

In order to setup the bot, you have to enable the Privileged Gateway Intents in the Discord Developer Portal for your application. 

Enabling all three Privileged Gateway Intents fixes the issue.
But there is no hint in the README documentation or Wiki which intents has to be enabled or can be left disabled.

### To Reproduce

During first startup via command `python bot.py`, the following error message appeares:

```
PS D:\Projects\Spark> python bot.py
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:Webserver:app is running in debug mode
Traceback (most recent call last):
  File "D:\Projects\Spark\bot.py", line 376, in <module>
    main()
  File "D:\Projects\Spark\bot.py", line 372, in main
    b.run(global_settings['TOKEN'])
  File "D:\Projects\Spark\bot.py", line 281, in run
    self.bot.run(token)
  File "C:\Python310\lib\site-packages\discord\client.py", line 715, in run
    return future.result()
  File "C:\Python310\lib\site-packages\discord\client.py", line 694, in runner
    await self.start(*args, **kwargs)
  File "C:\Python310\lib\site-packages\discord\client.py", line 658, in start
    await self.connect(reconnect=reconnect)
  File "C:\Python310\lib\site-packages\discord\client.py", line 599, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
```

### Expected behaviour

README should include a notice what `Privileged Gateway Intents` has to be enabled in the Discord Developer Portal.

### Screenshots

![grafik](https://user-images.githubusercontent.com/25348281/163836623-f6d5181e-60e2-4e94-80f8-6cf1643519f0.png)

**Comment by skillor** [comment]
It would also be nice if privileged Intents are not needed 😅
